from .a_pointer import APointerOptionsWidget
from .brush import BrushOptionsWidget
from .brush_arrow import BrushArrowOptionsWidget
from .crop import CropOptionsWidget
from .dashed_box import DashedBoxOptionsWidget
from .eraser import EraserOptionsWidget
from .eyedropper import EyedropperOptionsWidget
from .frame import FrameOptionsWidget
from .gradient import GradientOptionsWidget
from .move import MoveOptionsWidget
from .pen import PenOptionsWidget
from .pin import PinOptionsWidget
from .pointer_finger import PointerFingerOptionsWidget
from .polygon_lasso import PolygonLassoOptionsWidget
from .quick_selection import QuickSelectionOptionsWidget
from .rectangle import RectangleOptionsWidget
from .rotate_view import RotateViewOptionsWidget
from .spot_headling import SpotHeadlingOptionsWidget
from .stamp import StampOptionsWidget
from .text_options import TextOptionsWidget
